FROM python:3.10-slim

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install -r requirements.txt

# Копирование исходного кода
COPY creature.py .
COPY test.py .
COPY test_creature.py .

CMD ["python", "test.py"]